# Generated by Django 2.2 on 2019-08-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190808_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='core.Seller'),
            preserve_default=False,
        ),
    ]
