# Generated by Django 2.2 on 2019-08-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
    ]
